onboarding = false

[terminal]
new_cwd = "follow"

[keys]
new_workspace = ["prefix+shift+n", "alt+w"]
new_tab = ["prefix+c", "alt+t"]
new_pane = ["prefix+enter", "alt+n"]

focus_pane_left = ["prefix+h", "alt+h", "alt+left"]
focus_pane_down = ["prefix+j", "alt+j", "alt+down"]
focus_pane_up = ["prefix+k", "alt+k", "alt+up"]
focus_pane_right = ["prefix+l", "alt+l", "alt+right"]

previous_tab = ["prefix+p", "alt+shift+h"]
next_tab = ["prefix+n", "alt+shift+l"]

previous_agent = ["prefix+shift+k", "alt+shift+k"]
next_agent = ["prefix+shift+j", "alt+shift+j"]

close_pane = ["prefix+x", "ctrl+q"]
zoom = ["prefix+z", "prefix+f", "alt+m"]
split_horizontal = ["prefix+minus", "prefix+d"]
workspace_picker = ["prefix+w", "alt+s"]

resize_mode = ["prefix+r", "ctrl+n"]
copy_mode = ["prefix+[", "ctrl+s"]
toggle_float = "alt+f"


[keys.indexed]
agents = "alt"

[[keys.command]]
key = "alt+r"
type = "plugin_action"
command = "persiyanov.reviewr.toggle"

[[keys.command]]
key = "alt+shift+f"
type = "plugin_action"
command = "sessionizer.open"
description = "open project workspace"

[ui]
agent_panel_sort = "priority"
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
hide_tab_bar_when_single_tab = true
floating_pane_width = "80%"
floating_pane_height = "80%"

[theme]
name = "terminal"
auto_switch = false
