if status is-interactive
    alias ezsh="cd ~/.local/share chezmoi && nvim && chezmoi apply"
    alias szsh="source ~/.zshrc"
    alias efish="nvim ~/.config/fish/config.fish"
    alias sfish="source ~/.config/fish/config.fish"
    alias vim="nvim"
    alias vi="nvim"
    alias sv="sudoedit"
    alias so="sudo"
    alias ce="cd ~/.local/share/chezmoi && nvim && chezmoi apply && cd - && sfish"
    alias cadd="chezmoi add"
    alias ca="chezmoi apply"
    alias cdc="z chezmoi"
    alias dbc="distrobox create --clone base-arch-container --name"
    alias db="distrobox"
    alias dbe="distrobox enter"
    alias lg="lazygit"
    alias pnpx="pnpm dlx"
    alias fvf="fvm flutter"
    alias dvm="fvm dart"
    alias update-vms="sv /etc/libvirt/hooks/qemu"
    alias ga="git add ."
    alias gc="git checkout"
    alias gcs="git stash"
    alias gcsp="git stash pop"
    alias zj="zellij"
    alias gcb="git checkout -b"
    alias srmf="sudo rm -r"
    alias rmf="rm -r"
    alias syu="sudo pacman -Syu"
    alias sy="sudo pacman -S"
    alias artisan="php artisan"
    alias sail="./vendor/bin/sail"
    alias sart="./vendor/bin/sail artisan"
    alias part="./vendor/bin/sail php artisan"
    alias python="python3"
    alias set-user-owner='sudo chown -R $USER'
    alias set-user-perms='sudo chmod -R 775'
    alias dcupd='docker compose up --remove-orphans -d'
    alias dcdn='docker compose down'
    alias dc='docker'
    alias dci='docker exec -i'
    alias dcpull='docker compose pull'
    alias f="yazi"
    alias yays="yay -S"
    alias ls='eza -l -a'
    alias vf='vim $(fzf)'
    alias zu='z ..'
    alias zp='z -'
    alias typora="open -a typora"
    alias cl='claude'
    alias fcat='bat "$(fzf)"'
    alias fim='vim "$(fzf)"'
    alias fz='z "$(fd --type d | fzf)"'
end
